var x1 = { '@odata.etag': 'W/"HxmoUKH21EG0dQ8+D/IthQAAgBLe3A=="',
       id: 'AAMkADU4NTI4ODVhLTQ4M2YtNGQ3Yy04YTlmLTAxMDM0ZDU4NjE3MABGAAAAAADAYV23SKe4Tq7BDFEwbLESBwAfGahQofbUQbR1Dz4P8i2FAAAAAAENAAAfGahQofbUQbR1Dz4P8i2FAACAD2d8AAA=',
       createdDateTime: '2016-09-29T02:21:18.1747689Z',
       lastModifiedDateTime: '2016-09-29T02:21:21.362352Z',
       changeKey: 'HxmoUKH21EG0dQ8+D/IthQAAgBLe3A==',
       categories: [],
       originalStartTimeZone: 'China Standard Time',
       originalEndTimeZone: 'China Standard Time',
       responseStatus: { response: 'accepted', time: '2016-09-29T02:21:18.3153973Z' },
       iCalUId: '040000008200E00074C5B7101A82E0080000000008261E28F819D2010000000000000000100000000CC255CE228DFB4BAA75D8F0B3B6F6B5',
       reminderMinutesBeforeStart: 15,
       isReminderOn: false,
       hasAttachments: false,
       subject: '李潇琳 ',
       body: { contentType: 'text', content: '' },
       bodyPreview: '',
       importance: 'normal',
       sensitivity: 'normal',
       start: { dateTime: '2016-09-29T02:30:00.0000000', timeZone: 'UTC' },
       end: { dateTime: '2016-09-29T03:30:00.0000000', timeZone: 'UTC' },
       location:
        { displayName: '效率(2楼大会议室)',
          address:
           { street: '',
             city: '',
             state: '',
             countryOrRegion: '',
             postalCode: '' } },
       isAllDay: false,
       isCancelled: false,
       isOrganizer: false,
       recurrence: null,
       responseRequested: true,
       seriesMasterId: null,
       showAs: 'busy',
       type: 'singleInstance',
       attendees:
        [ { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '李潇琳', address: 'lixiaolin@baixing.com' } } ],
       organizer: { emailAddress: { name: '李潇琳', address: 'lixiaolin@baixing.com' } },
       webLink: 'https://partner.outlook.cn/owa/?ItemID=AAMkADU4NTI4ODVhLTQ4M2YtNGQ3Yy04YTlmLTAxMDM0ZDU4NjE3MABGAAAAAADAYV23SKe4Tq7BDFEwbLESBwAfGahQofbUQbR1Dz4P8i2FAAAAAAENAAAfGahQofbUQbR1Dz4P8i2FAACAD2d8AAA%3D&exvsurl=1&viewModel=ICalendarItemDetailsViewModelFactory' }
var x2 = { '@odata.etag': 'W/"GCbTg4Z2Y0CpDErXZSzU4gAAkXQANw=="',
       id: 'AAMkAGMwMGRlMWViLTQ1MDItNDkzYS1iYzNlLTZkMDIxYzkyMjQyOABGAAAAAAB072CXRszdQKiAhgxH2ejIBwAYJtODhnZjQKkMStdlLNTiAAAAAAENAAAYJtODhnZjQKkMStdlLNTiAACRVd1KAAA=',
       createdDateTime: '2016-09-29T02:21:16.281396Z',
       lastModifiedDateTime: '2016-09-29T02:21:19.6096067Z',
       changeKey: 'GCbTg4Z2Y0CpDErXZSzU4gAAkXQANw==',
       categories: [],
       originalStartTimeZone: 'China Standard Time',
       originalEndTimeZone: 'China Standard Time',
       responseStatus: { response: 'organizer', time: '0001-01-01T00:00:00Z' },
       iCalUId: '040000008200E00074C5B7101A82E0080000000008261E28F819D2010000000000000000100000000CC255CE228DFB4BAA75D8F0B3B6F6B5',
       reminderMinutesBeforeStart: 15,
       isReminderOn: true,
       hasAttachments: false,
       subject: '二手货车',
       body:
        { contentType: 'html',
          content: '<html>\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n<meta content="text/html; charset=gb2312">\r\n<style type="text/css" style="display:none">\r\n<!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n-->\r\n</style>\r\n</head>\r\n<body dir="ltr">\r\n<div id="divtagdefaultwrapper" style="font-size:10pt; color:#000000; background-color:#FFFFFF; font-family:\'Microsoft YaHei\',\'微软雅黑\',Sans-Serif">\r\n<p><br>\r\n</p>\r\n</div>\r\n</body>\r\n</html>\r\n' },
       bodyPreview: '',
       importance: 'normal',
       sensitivity: 'normal',
       start: { dateTime: '2016-09-29T02:30:00.0000000', timeZone: 'UTC' },
       end: { dateTime: '2016-09-29T03:30:00.0000000', timeZone: 'UTC' },
       location:
        { displayName: '效率(2楼大会议室)',
          address:
           { street: '',
             city: '',
             state: '',
             countryOrRegion: '',
             postalCode: '' } },
       isAllDay: false,
       isCancelled: false,
       isOrganizer: true,
       recurrence: null,
       responseRequested: true,
       seriesMasterId: null,
       showAs: 'busy',
       type: 'singleInstance',
       attendees:
        [ { status: { response: 'accepted', time: '2016-09-29T02:21:18.3153973Z' },
            type: 'resource',
            emailAddress:
             { name: '效率(2楼大会议室)',
               address: 'lianmengmeetingroom@baixing.com' } } ],
       organizer: { emailAddress: { name: '李潇琳', address: 'lixiaolin@baixing.com' } },
       webLink: 'https://partner.outlook.cn/owa/?ItemID=AAMkAGMwMGRlMWViLTQ1MDItNDkzYS1iYzNlLTZkMDIxYzkyMjQyOABGAAAAAAB072CXRszdQKiAhgxH2ejIBwAYJtODhnZjQKkMStdlLNTiAAAAAAENAAAYJtODhnZjQKkMStdlLNTiAACRVd1KAAA%3D&exvsurl=1&viewModel=ICalendarItemDetailsViewModelFactory' }
var x3 =     { '@odata.etag': 'W/"GCbTg4Z2Y0CpDErXZSzU4gAAkXQAMw=="',
       id: 'AAMkAGMwMGRlMWViLTQ1MDItNDkzYS1iYzNlLTZkMDIxYzkyMjQyOAFRAAgI0_f7jlNAAEYAAAAAdO9gl0bM3UCogIYMR9noyAcAGCbTg4Z2Y0CpDErXZSzU4gAAAAABDQAAGCbTg4Z2Y0CpDErXZSzU4gAAgwnhHgAAEA==',
       createdDateTime: '2016-09-01T01:40:51.3203335Z',
       lastModifiedDateTime: '2016-09-29T02:15:49.1011262Z',
       changeKey: 'GCbTg4Z2Y0CpDErXZSzU4gAAkXQAMw==',
       categories: [],
       originalStartTimeZone: 'China Standard Time',
       originalEndTimeZone: 'China Standard Time',
       responseStatus: { response: 'accepted', time: '2016-09-01T02:08:19.7916741Z' },
       iCalUId: '040000008200E00074C5B7101A82E00807E0091DE07E2A653404D201000000000000000010000000ADA03F4D3C241D4192F0C36435F6599C',
       reminderMinutesBeforeStart: 15,
       isReminderOn: true,
       hasAttachments: false,
       subject: '二手货车/工程车 沟通周会',
       body:
        { contentType: 'html',
          content: '<html>\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n<meta content="text/html; charset=gb2312">\r\n<meta content="text/html; charset=gb2312">\r\n<meta name="Generator" content="Microsoft Word 15 (filtered medium)">\r\n<style>\r\n<!--\r\n@font-face\r\n\t{font-family:"Cambria Math"}\r\na:link, span.MsoHyperlink\r\n\t{color:#0563C1;\r\n\ttext-decoration:underline}\r\na:visited, span.MsoHyperlinkFollowed\r\n\t{color:#954F72;\r\n\ttext-decoration:underline}\r\n@page WordSection1\r\n\t{margin:72.0pt 90.0pt 72.0pt 90.0pt}\r\n-->\r\n</style>\r\n</head>\r\n<body lang="ZH-CN" link="#0563C1" vlink="#954F72" style="">\r\n<div class="WordSection1">\r\n<p class="MsoNormal"><span lang="EN-US">&nbsp;</span></p>\r\n</div>\r\n</body>\r\n</html>\r\n' },
       bodyPreview: '',
       importance: 'normal',
       sensitivity: 'normal',
       start: { dateTime: '2016-09-29T02:30:00.0000000', timeZone: 'UTC' },
       end: { dateTime: '2016-09-29T03:30:00.0000000', timeZone: 'UTC' },
       location: { displayName: '琴房(1806)' },
       isAllDay: false,
       isCancelled: false,
       isOrganizer: false,
       recurrence: null,
       responseRequested: true,
       seriesMasterId: 'AAMkAGMwMGRlMWViLTQ1MDItNDkzYS1iYzNlLTZkMDIxYzkyMjQyOABGAAAAAAB072CXRszdQKiAhgxH2ejIBwAYJtODhnZjQKkMStdlLNTiAAAAAAENAAAYJtODhnZjQKkMStdlLNTiAACDCeEeAAA=',
       showAs: 'busy',
       type: 'occurrence',
       attendees:
        [ { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '朱轶林', address: 'zhuyilin@baixing.com' } },
          { status: { response: 'accepted', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '李潇琳', address: 'lixiaolin@baixing.com' } },
          { status: { response: 'accepted', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '杨冰青', address: 'yangbingqing@baixing.com' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '赵立军', address: 'zhaolijun@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '陈书勇', address: 'chenshuyong@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress:
             { name: 'dushaowei@baixing.com.cn',
               address: 'dushaowei@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '付攀', address: 'fupan@baixing.com' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: 'shijiaqun', address: 'shijiaqun@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: '谭瑶', address: 'tanyao@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress:
             { name: 'guoyawei@baixing.com.cn',
               address: 'guoyawei@baixing.com.cn' } },
          { status: { response: 'none', time: '0001-01-01T00:00:00Z' },
            type: 'required',
            emailAddress: { name: 'guoyawei1', address: 'guoyawei1@baixing.com.cn' } } ],
       organizer: { emailAddress: { name: '朱轶林', address: 'zhuyilin@baixing.com' } },
       webLink: 'https://partner.outlook.cn/owa/?ItemID=AAMkAGMwMGRlMWViLTQ1MDItNDkzYS1iYzNlLTZkMDIxYzkyMjQyOAFRAAgI0%2Bf7jlNAAEYAAAAAdO9gl0bM3UCogIYMR9noyAcAGCbTg4Z2Y0CpDErXZSzU4gAAAAABDQAAGCbTg4Z2Y0CpDErXZSzU4gAAgwnhHgAAEA%3D%3D&exvsurl=1&viewModel=ICalendarItemDetailsViewModelFactory' }
